AspnetMVCPatient/Models/PatientDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AspnetMVCPatient.Models
{
    public class PatientDetail
    {
        public int PatientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DOB { get; set; }
    }
}

AspnetMVCPatient/Models/PatientMetricsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AspnetMVCPatient.Models
{
    public class PatientMetricsViewModel
    {
        public PatientMetricsViewModel()
        {

        }
        public IEnumerable<PatientDetail> Patients { get; set; }

    }
}

AspnetMVCPatient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspnetMVCPatient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AspnetMVCPatient/Controllers/PatientController.cs
using AspnetMVCPatient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspnetMVCPatient.Controllers
{
    public class PatientController : Controller
    {
        List<PatientDetail> pats = new List<PatientDetail>();

        public ActionResult Index()
        {
            pats.Add(new PatientDetail { PatientID = 100, FirstName = "Mike", LastName = "Tyson", DOB = Convert.ToDateTime("2021-05-06") });
            pats.Add(new PatientDetail { PatientID = 200, FirstName = "Brind", LastName = "Smith", DOB = Convert.ToDateTime("2016-01-30") });
            pats.Add(new PatientDetail { PatientID = 300, FirstName = "Woo", LastName = "Micrare", DOB = Convert.ToDateTime("1968-12-06") });
            pats.Add(new PatientDetail { PatientID = 400, FirstName = "Lynch", LastName = "William", DOB = Convert.ToDateTime("1998-01-26") });

            PatientMetricsViewModel vm = new PatientMetricsViewModel();
            vm.Patients = pats;
            return View("Index", vm);

        }
    }
}

AspnetMVCPatient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

AspnetMVCPatient/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

AspnetMVCPatient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

AspnetMVCPatient/Views/Patient/Index.cshtml
@model AspnetMVCPatient.Models.PatientMetricsViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="container-fluid">
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Patient ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>DOB</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model.Patients)
            {
                <tr>
                    <td class="col">
                        @p.PatientID
                    </td>
                    <td class="col">
                        @p.FirstName
                    </td>
                    <td class="col">
                        @p.LastName
                    </td>
                    <td class="col">
                        @p.DOB
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

AspnetMVCPatient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Patients", "Index", "Patient", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>